### ISSUE TITLE
pigeon classification doesn't work (Chinese Hamster)

### ISSUE THREAD

**Issue by yesh1m** [PacificBiosciences/pbbioconda#682] opened 2024-05-02 13:00 UTC
1. Sample Data : Kinnex Full-length RNA, "collapsed.sorted.gff" from SMRTLink v13.0 & command line
2. Reference Data : Chinese hamster (CriGri_1.0) ; downloaded from Ensembl 
[genomic.modified.sorted.zip](https://github.com/PacificBiosciences/pbbioconda/files/15188581/genomic.modified.sorted.zip)

3. Used command: pigeon classify -d classify --log-level TRACE --log-file classify.log  collapsed.sorted.gff ./genomic.modified.sorted.gtf  ./Cricetulus_griseus_crigri.CriGri_1.0.dna.toplevel.fa

4. Problem : The classification job does not produce final classification.txt with summary.txt and report.json - only tmp file with scaffold name (created until JH000801) 
![image](https://github.com/PacificBiosciences/pbbioconda/assets/166366130/3532cc68-cab8-453a-8912-fd3f7c48cbae)

The total transcript is 454,686 but the log stopped at 405,800.
![image](https://github.com/PacificBiosciences/pbbioconda/assets/166366130/6bf660fd-292a-4b04-a192-f2dad07fb427)

5. Could you please review the GTF and find the root cause of this?

**Comment by WillCh07** [comment] 2024-05-09 20:23
How did you get the "collapsed.sorted.gff" from the SMRT Link, did you use the same reference?

**Comment by yesh1m** [comment] 2024-05-10 01:16
They got the file from output directory of SMRTLink by using the same reference FASTA file from Ensembl. 
Also, they tried the analysis via command line started from hifi.bam but encountered same issue.

**Comment by WillCh07** [comment] 2024-05-14 05:47
Have they checked their analysis status, like ram usage (htop), it looks like there are too many scaffolds and contigs to accomplish the analysis.

**Comment by yesh1m** [comment] 2024-05-14 05:55
Yes, after certain JH#, the process disappears without any message. Do you think specifying the number of threads to use via the '-j' option might address this issue?

**Comment by armintoepfer** [comment] 2024-06-24 15:23
We can't help you with data processing. If you provide a small reproducible test case, we can have a look. Closing until reproducible case is available.

**Closed by armintoepfer** 2024-06-24 15:23 UTC
Labels: IsoSeq
