### ISSUE TITLE
Error No space left on device

### ISSUE THREAD

**Issue by ardy20** [PacificBiosciences/pbbioconda#508] opened 2022-05-30 06:54 UTC
Dear Developer

I get the following error in ovl stage. Could you please advise whether this is a RAM issue or space issue?

sort: write failed: /tmp/sortpARWRt: No space left on device
2416.01user 478.34system 1:04:02elapsed 75%CPU (0avgtext+0avgdata 5220maxresident)k
128inputs+808227152outputs (1major+41797minor)pagefaults 0swaps
[Sun May 29 17:11:24 2022]
Error in rule ovl_asym_merge:
    jobid: 13
    output: 05-ovl_asym_merge/ovl.merged.m4, 05-ovl_asym_merge/ovl.nonlocal.m4
    shell:

        wd=$(dirname 05-ovl_asym_merge/ovl.merged.m4)
        mkdir -p $wd
        cd $wd
        rel=..

        # We must change rel-path names when we chdir.
        for fn in 04-ovl_asym_run/7/ovl.sorted.m4 04-ovl_asym_run/25/ovl.sorted.m4 04-ovl_asym_run/4/ovl.sorted.m4 04-ovl_asym_run/32/ovl.sorted.m4 04-ovl_asym_run/22/ovl.sorted.m4 04-ovl_asorted.m4 04-ovl_asym_run/6/ovl.sorted.m4 04-ovl_asym_run/0/ovl.sorted.m4 04-ovl_asym_run/13/ovl.sorted.m4 04-ovl_asym_run/3/ovl.sorted.m4 04-ovl_asym_run/19/ovl.sorted.m4 04-ovl_asym_run/204-ovl_asym_run/21/ovl.sorted.m4 04-ovl_asym_run/35/ovl.sorted.m4 04-ovl_asym_run/33/ovl.sorted.m4 04-ovl_asym_run/16/ovl.sorted.m4 04-ovl_asym_run/12/ovl.sorted.m4 04-ovl_asym_run/1/ovl.soasym_run/31/ovl.sorted.m4 04-ovl_asym_run/18/ovl.sorted.m4 04-ovl_asym_run/15/ovl.sorted.m4 04-ovl_asym_run/38/ovl.sorted.m4 04-ovl_asym_run/27/ovl.sorted.m4 04-ovl_asym_run/34/ovl.sorted.mun/10/ovl.sorted.m4 04-ovl_asym_run/5/ovl.sorted.m4 04-ovl_asym_run/2/ovl.sorted.m4 04-ovl_asym_run/30/ovl.sorted.m4 04-ovl_asym_run/20/ovl.sorted.m4 04-ovl_asym_run/11/ovl.sorted.m4 04-ovll.sorted.m4 04-ovl_asym_run/39/ovl.sorted.m4 04-ovl_asym_run/9/ovl.sorted.m4 04-ovl_asym_run/37/ovl.sorted.m4 04-ovl_asym_run/29/ovl.sorted.m4; do
            echo $rel/$fn
        done >| ./sorted.fofn

        input_fofn=./sorted.fofn         params_num_threads="24"         params_db_prefix=reads         params_config_sh_fn="$rel/01-generate_config/generated.config"         params_log_lev    time ipa2-task ovl_asym_merge

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job ovl_asym_merge since they might be corrupted:
05-ovl_asym_merge/ovl.merged.m4
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /scratch/project_mnt/S0030/ipa2/RUN/.snakemake/log/2022-05-27T085154.649998.snakemake.log
ERROR: Command '/scratch/project/qaafi-cnafs/ipa2/bin/python3 -m snakemake -j 1 -d RUN -p -s /scratch/project/qaafi-cnafs/ipa2/etc/ipa.snakefile --configfile RUN/config.yaml --reason' retur
Exiting.

**Comment by isovic** [comment] 2022-06-07 13:20
Hi,

This error refers to disk space, concretely, the one available in your `/tmp` directory.
Some systems don't have a large `/tmp` dir set up. In this case, you may specify a custom temporary directory used for sorting using the following option:
```
  --tmp-dir TMP_DIR     Temporary directory for some disk based operations like sorting. (default: /tmp)
```
I would suggest specifying --tmp-dir "./".

I'm closing this issue because it's mostly a duplicate of:
https://github.com/PacificBiosciences/pbbioconda/issues/510

Best regards,
Ivan.

**Closed by isovic** 2022-06-07 13:20 UTC
