### ISSUE TITLE
Exception: FATAL ERROR: Cycles in the graph?

### ISSUE THREAD

**Issue by gbdias** [PacificBiosciences/pbbioconda#69] opened 2019-01-07 21:08 UTC
Hi,

- I am trying to assemble a genome using the pb-assembly conda package (v0.0.1).
- As input for the assembly I am using an HGAP4 output `pbcoretools.tasks.gather_fasta-1/file.fasta`, which if I understand correctly is the merged file of all reads, converted from bax.h5 to bam and then to fasta.
- As input to Falcon Unzip I am using a .fofn with the pbsmrtpipe bax.h5 files converted to bam `pbcoretools.tasks.h5_subreads_to_subread-*/*.subreads.bam`
- Although the assembly seems to be completing without errors, the unzipping part is throwing the error below.
- Here is the end of the **unzip** log file.
```
[INFO]Num satisfied in this iteration: 1
[INFO]Num still unsatisfied: 239
[INFO]About to submit: Node(3-unzip/0-phasing/000243F)
[INFO]Popen: 'bash -C /home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/pwatcher/mains/job_start.sh >| /scratch/gd98309/S2/assemblies/funzip_s2_run3/3-unzip/0-phasing/000243F/run-P26debfbbb3e00d.bash.stdout 2>| /scratch/gd98309/S2/assemblies/funzip_s2_run3/3-unzip/0-phasing/000243F/run-P26debfbbb3e00d.bash.stderr'
[ERROR]Task Node(3-unzip/0-phasing/000243F) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: set([Node(3-unzip/0-phasing/000243F)])
[ERROR]ready: set([Node(3-unzip/0-phasing/000550F), Node(3-unzip/0-phasing/000340F), Node(3-unzip/0-phasing/000210F), Node(3-unzip/0-phasing/000621F), Node(3-unzip/0-phasing/000204F), Node(3-unzip/0-phasing/000339F), Node(3-unzip/0-phasing/000612F), Node(3-unzip/0-phasing/000609F), Node(3-unzip/0-phasing/000779F), Node(3-unzip/0-phasing/000199F), Node(3-unzip/0-phasing/000421F), Node(3-unzip/0-phasing/000016F), Node(3-unzip/0-phasing/000622F), Node(3-unzip/0-phasing/000585F), Node(3-unzip/0-phasing/000677F), Node(3-unzip/0-phasing/000735F), Node(3-unzip/0-phasing/000594F), Node(3-unzip/0-phasing/000496F), Node(3-unzip/0-phasing/000366F), Node(3-unzip/0-phasing/000020F), Node(3-unzip/0-phasing/000349F), Node(3-unzip/0-phasing/000013F), Node(3-unzip/0-phasing/000731F), Node(3-unzip/0-phasing/000061F), Node(3-unzip/0-phasing/000450F), Node(3-unzip/0-phasing/000166F), Node(3-unzip/0-phasing/000376F), Node(3-unzip/0-phasing/000454F), Node(3-unzip/0-phasing/000005F), Node(3-unzip/0-phasing/000327F), Node(3-unzip/0-phasing/000605F), Node(3-unzip/0-phasing/000770F), Node(3-unzip/0-phasing/000789F), Node(3-unzip/0-phasing/000552F), Node(3-unzip/0-phasing/000304F), Node(3-unzip/0-phasing/000467F), Node(3-unzip/0-phasing/000460F), Node(3-unzip/0-phasing/000608F), Node(3-unzip/0-phasing/000131F), Node(3-unzip/0-phasing/000305F), Node(3-unzip/0-phasing/000331F), Node(3-unzip/0-phasing/000537F), Node(3-unzip/0-phasing/000048F), Node(3-unzip/0-phasing/000600F), Node(3-unzip/0-phasing/000355F), Node(3-unzip/0-phasing/000307F), Node(3-unzip/0-phasing/000589F), Node(3-unzip/0-phasing/000004F), Node(3-unzip/0-phasing/000179F), Node(3-unzip/0-phasing/000647F), Node(3-unzip/0-phasing/000653F), Node(3-unzip/0-phasing/000465F), Node(3-unzip/0-phasing/000445F), Node(3-unzip/0-phasing/000408F), Node(3-unzip/0-phasing/000103F), Node(3-unzip/0-phasing/000840F), Node(3-unzip/0-phasing/000602F), Node(3-unzip/0-phasing/000814F), Node(3-unzip/0-phasing/000124F), Node(3-unzip/0-phasing/000393F), Node(3-unzip/0-phasing/000330F), Node(3-unzip/0-phasing/000549F), Node(3-unzip/0-phasing/000468F), Node(3-unzip/0-phasing/000281F), Node(3-unzip/0-phasing/000648F), Node(3-unzip/0-phasing/000161F), Node(3-unzip/0-phasing/000529F), Node(3-unzip/0-phasing/000042F), Node(3-unzip/0-phasing/000228F), Node(3-unzip/0-phasing/000443F), Node(3-unzip/0-phasing/000272F), Node(3-unzip/0-phasing/000217F), Node(3-unzip/0-phasing/000492F), Node(3-unzip/0-phasing/000150F), Node(3-unzip/0-phasing/000625F), Node(3-unzip/0-phasing/000476F), Node(3-unzip/0-phasing/000449F), Node(3-unzip/0-phasing/000112F), Node(3-unzip/0-phasing/000163F), Node(3-unzip/0-phasing/000462F), Node(3-unzip/0-phasing/000086F), Node(3-unzip/0-phasing/000564F), Node(3-unzip/0-phasing/000239F), Node(3-unzip/0-phasing/000424F), Node(3-unzip/0-phasing/000657F), Node(3-unzip/0-phasing/000208F), Node(3-unzip/0-phasing/000578F), Node(3-unzip/0-phasing/000633F), Node(3-unzip/0-phasing/000300F), Node(3-unzip/0-phasing/000356F), Node(3-unzip/0-phasing/000486F), Node(3-unzip/0-phasing/000162F), Node(3-unzip/0-phasing/000526F), Node(3-unzip/0-phasing/000257F), Node(3-unzip/0-phasing/000023F), Node(3-unzip/0-phasing/000369F), Node(3-unzip/0-phasing/000302F), Node(3-unzip/0-phasing/000064F), Node(3-unzip/0-phasing/000314F), Node(3-unzip/0-phasing/000242F), Node(3-unzip/0-phasing/000347F), Node(3-unzip/0-phasing/000038F), Node(3-unzip/0-phasing/000072F), Node(3-unzip/0-phasing/000533F), Node(3-unzip/0-phasing/000309F), Node(3-unzip/0-phasing/000645F), Node(3-unzip/0-phasing/000591F), Node(3-unzip/0-phasing/000557F), Node(3-unzip/0-phasing/000739F), Node(3-unzip/0-phasing/000034F), Node(3-unzip/0-phasing/000123F), Node(3-unzip/0-phasing/000130F), Node(3-unzip/0-phasing/000616F), Node(3-unzip/0-phasing/000568F), Node(3-unzip/0-phasing/000193F), Node(3-unzip/0-phasing/000688F), Node(3-unzip/0-phasing/000371F), Node(3-unzip/0-phasing/000157F), Node(3-unzip/0-phasing/000672F), Node(3-unzip/0-phasing/000346F), Node(3-unzip/0-phasing/000787F), Node(3-unzip/0-phasing/000321F), Node(3-unzip/0-phasing/000222F), Node(3-unzip/0-phasing/000521F), Node(3-unzip/0-phasing/000372F), Node(3-unzip/0-phasing/000230F), Node(3-unzip/0-phasing/000006F), Node(3-unzip/0-phasing/000066F), Node(3-unzip/0-phasing/000141F), Node(3-unzip/0-phasing/000292F), Node(3-unzip/0-phasing/000337F), Node(3-unzip/0-phasing/000436F), Node(3-unzip/0-phasing/000351F), Node(3-unzip/0-phasing/000361F), Node(3-unzip/0-phasing/000556F), Node(3-unzip/0-phasing/000368F), Node(3-unzip/0-phasing/000484F), Node(3-unzip/0-phasing/000012F), Node(3-unzip/0-phasing/000328F), Node(3-unzip/0-phasing/000039F), Node(3-unzip/0-phasing/000394F), Node(3-unzip/0-phasing/000151F), Node(3-unzip/0-phasing/000370F), Node(3-unzip/0-phasing/000010F), Node(3-unzip/0-phasing/000474F), Node(3-unzip/0-phasing/000177F), Node(3-unzip/0-phasing/000282F), Node(3-unzip/0-phasing/000588F), Node(3-unzip/0-phasing/000090F), Node(3-unzip/0-phasing/000171F), Node(3-unzip/0-phasing/000338F), Node(3-unzip/0-phasing/000659F), Node(3-unzip/0-phasing/000037F), Node(3-unzip/0-phasing/000333F), Node(3-unzip/0-phasing/000102F), Node(3-unzip/0-phasing/000611F), Node(3-unzip/0-phasing/000615F), Node(3-unzip/0-phasing/000058F), Node(3-unzip/0-phasing/000275F), Node(3-unzip/0-phasing/000154F), Node(3-unzip/0-phasing/000244F), Node(3-unzip/0-phasing/000269F), Node(3-unzip/0-phasing/000312F), Node(3-unzip/0-phasing/000255F), Node(3-unzip/0-phasing/000326F), Node(3-unzip/0-phasing/000656F), Node(3-unzip/0-phasing/000017F), Node(3-unzip/0-phasing/000447F), Node(3-unzip/0-phasing/000471F), Node(3-unzip/0-phasing/000088F), Node(3-unzip/0-phasing/000666F), Node(3-unzip/0-phasing/000593F), Node(3-unzip/0-phasing/000545F), Node(3-unzip/0-phasing/000148F), Node(3-unzip/0-phasing/000336F), Node(3-unzip/0-phasing/000404F), Node(3-unzip/0-phasing/000267F), Node(3-unzip/0-phasing/000052F), Node(3-unzip/0-phasing/000755F), Node(3-unzip/0-phasing/000104F), Node(3-unzip/0-phasing/000241F), Node(3-unzip/0-phasing/000149F), Node(3-unzip/0-phasing/000252F), Node(3-unzip/0-phasing/000291F), Node(3-unzip/0-phasing/000240F), Node(3-unzip/0-phasing/000658F), Node(3-unzip/0-phasing/000528F), Node(3-unzip/0-phasing/000398F), Node(3-unzip/0-phasing/000791F), Node(3-unzip/0-phasing/000202F), Node(3-unzip/0-phasing/000262F), Node(3-unzip/0-phasing/000544F), Node(3-unzip/0-phasing/000381F), Node(3-unzip/0-phasing/000182F), Node(3-unzip/0-phasing/000678F), Node(3-unzip/0-phasing/000811F), Node(3-unzip/0-phasing/000100F), Node(3-unzip/0-phasing/000290F), Node(3-unzip/0-phasing/000080F), Node(3-unzip/0-phasing/000094F), Node(3-unzip/0-phasing/000021F), Node(3-unzip/0-phasing/000448F), Node(3-unzip/0-phasing/000060F), Node(3-unzip/0-phasing/000276F), Node(3-unzip/0-phasing/000531F), Node(3-unzip/0-phasing/000732F), Node(3-unzip/0-phasing/000140F), Node(3-unzip/0-phasing/000099F), Node(3-unzip/0-phasing/000580F), Node(3-unzip/0-phasing/000062F), Node(3-unzip/0-phasing/000284F), Node(3-unzip/0-phasing/000067F), Node(3-unzip/0-phasing/000264F), Node(3-unzip/0-phasing/000107F), Node(3-unzip/0-phasing/000493F), Node(3-unzip/0-phasing/000133F), Node(3-unzip/0-phasing/000092F), Node(3-unzip/0-phasing/000031F), Node(3-unzip/0-phasing/000118F), Node(3-unzip/0-phasing/000655F), Node(3-unzip/0-phasing/000114F), Node(3-unzip/0-phasing/000431F), Node(3-unzip/0-phasing/000781F), Node(3-unzip/0-phasing/000091F), Node(3-unzip/0-phasing/000771F), Node(3-unzip/0-phasing/000697F), Node(3-unzip/0-phasing/000041F), Node(3-unzip/0-phasing/000665F), Node(3-unzip/0-phasing/000289F), Node(3-unzip/0-phasing/000482F), Node(3-unzip/0-phasing/000110F), Node(3-unzip/0-phasing/000122F), Node(3-unzip/0-phasing/000144F), Node(3-unzip/0-phasing/000489F), Node(3-unzip/0-phasing/000357F), Node(3-unzip/0-phasing/000455F), Node(3-unzip/0-phasing/000694F)])
	submitted: set([])
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
Traceback (most recent call last):
  File "/home/gd98309/.conda/envs/falconda/bin/fc_unzip.py", line 11, in <module>
    load_entry_point('falcon-unzip==1.1.3', 'console_scripts', 'fc_unzip.py')()
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_unzip/mains/start_unzip.py", line 29, in main
    unzip.run(**vars(args))
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 147, in run
    unzip_all(config)
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 28, in unzip_all
    tasks_unzip.run_workflow(wf, config, rule_writer)
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_unzip/tasks/unzip.py", line 437, in run_workflow
    dist=Dist(NPROC=24, job_dict=config['job.step.unzip.blasr_aln']),
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_kit/pype.py", line 194, in gen_parallel_tasks
    wf.refreshTargets()
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 277, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 361, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(3-unzip/0-phasing/000243F)])
```

- And here is the end of the task specific log file `/scratch/gd98309/S2/assemblies/funzip_s2_run3/3-unzip/0-phasing/000243F/run-P26debfbbb3e00d.bash.stderr`.

```
Traceback (most recent call last):
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 637, in <module>
    main()
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 634, in main
    run(**vars(args))
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 499, in run
    all_regions = delineate_regions(ctg_id, p_paths[ctg_id], a_paths, a_placement_for_ctg)
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 341, in delineate_regions
    raise Exception(msg)
Exception: FATAL ERROR: Cycles in the graph? w='000223649:B', len(in_edges)=1
WARNING:root:Call '/bin/bash user_script.sh' returned 256.
WARNING:root:CD: 'uow-00' -> '/scratch/gd98309/S2/assemblies/funzip_s2_run3/3-unzip/0-phasing/000243F'
Traceback (most recent call last):
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 116, in <module>
    main()
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 112, in main
    run(**vars(args))
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 65, in run
    pypeflow.do_task.run_bash(script, inputs, outputs, params)
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/pypeflow/do_task.py", line 187, in run_bash
    util.system(cmd)
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
2018-12-29 06:31:36,368 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2018-12-29 06:31:36,368 - root - WARNING - CD: '/scratch/gd98309/S2/assemblies/funzip_s2_run3/3-unzip/0-phasing/000243F' -> '/scratch/gd98309/S2/assemblies/funzip_s2
_run3/3-unzip/0-phasing/000243F'
2018-12-29 06:31:36,369 - root - WARNING - CD: '/scratch/gd98309/S2/assemblies/funzip_s2_run3/3-unzip/0-phasing/000243F' -> '/scratch/gd98309/S2/assemblies/funzip_s2
_run3/3-unzip/0-phasing/000243F'
2018-12-29 06:31:36,369 - root - CRITICAL - Error in /home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/scra
tch/gd98309/S2/assemblies/funzip_s2_run3/3-unzip/0-phasing/000243F/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/pypeflow/do_task.py", line 267, in <module>
    main()
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/pypeflow/do_task.py", line 259, in main
    run(**vars(parsed_args))
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/pypeflow/do_task.py", line 253, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/pypeflow/do_task.py", line 228, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/pypeflow/do_task.py", line 187, in run_bash
    util.system(cmd)
  File "/home/gd98309/.conda/envs/falconda/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
+++ pwd
++ echo 'FAILURE. Running top in /scratch/gd98309/S2/assemblies/funzip_s2_run3/3-unzip/0-phasing/000243F (If you see -terminal database is inaccessible- you are usin
g the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real	0m36.386s
user	0m38.761s
sys	0m4.958s
+ finish
+ echo 'finish code: 1'
```

- I have tried running Unzip a few times and the phasing step always crashed at the same point, on contig 000243F.
- Here is the fasta header for this contig:
`>000243F 000142541:E~000193175:B~000223649:B~000223649:B ctg_linear 149887 476253`
- I have also tried starting the assembly from scratch and the same contig 000243F gives me the error again.
- Do you see anything obviously wrong with this contig header? I noticed there is a repeated node ID `~000223649:B~000223649:B` in the header, and that this is part of the error message, but I don't know what that means.
- I am currently repeating the assembly and unzipping with the latest pb-assembly (v.0.0.2) to see if that solves the problem. Any comments are appreciated.

Thanks

**Comment by gbdias** [comment] 2019-01-09 19:58
- [ ] edit contig header and try unzip again

**Comment by gbdias** [comment] 2019-01-15 16:09
- Repeating the assembly with the newest version of pb-assembly did not solve the problem.
- I get the same error at the same contig ID for a totally new assembly.
- Here is part of the log file in `3-unzip/0-phasing/000243F/run-Pc6667d54abf08b.bash.stderr`
```
python -m falcon_unzip.proto.main_augment_pb     --wd ./proto/     --ctg-id 000243F     --p-ctg ${falcon_asm_dir}/p_ctg.fa     --p-ctg-tiling-path $
{falcon_asm_dir}/p_ctg_tiling_path     --a-ctg ${falcon_asm_dir}/a_ctg.fa     --a-ctg-tiling-path ${falcon_asm_dir}/a_ctg_tiling_path     --p-varian
t-fn get_phased_blocks/phased_variants     --preads-sam proto/preads.sam     --extracted-ctg-fasta ${unzip_dir}/reads/000243F/ref.fa     --rawread-b
am ${ctg_aln_out}     --rid-phase-map rid_to_phase.true     --out-updated-rid-phase_map rid_to_phase.tmp
+ python -m falcon_unzip.proto.main_augment_pb --wd ./proto/ --ctg-id 000243F --p-ctg /scratch/gd98309/S2/assemblies/funzip_s2_run5/2-asm-falcon/p_c
tg.fa --p-ctg-tiling-path /scratch/gd98309/S2/assemblies/funzip_s2_run5/2-asm-falcon/p_ctg_tiling_path --a-ctg /scratch/gd98309/S2/assemblies/funzip
_s2_run5/2-asm-falcon/a_ctg.fa --a-ctg-tiling-path /scratch/gd98309/S2/assemblies/funzip_s2_run5/2-asm-falcon/a_ctg_tiling_path --p-variant-fn get_p
hased_blocks/phased_variants --preads-sam proto/preads.sam --extracted-ctg-fasta /scratch/gd98309/S2/assemblies/funzip_s2_run5/3-unzip/reads/000243F
/ref.fa --rawread-bam alignment/000243F_sorted.bam --rid-phase-map rid_to_phase.true --out-updated-rid-phase_map rid_to_phase.tmp
falcon-unzip 1.1.4
falcon-kit 1.2.4
pypeflow 2.1.1
Traceback (most recent call last):
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 627, in <module>
    main()
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 624, in main
    run(**vars(args))
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 489, in run
    all_regions = delineate_regions(ctg_id, p_paths[ctg_id], a_paths, a_placement_for_ctg)
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 333, in delineate_regions
    raise Exception(msg)
Exception: FATAL ERROR: Cycles in the graph? w='000223649:B', len(in_edges)=1
WARNING:root:Call '/bin/bash user_script.sh' returned 256.
WARNING:root:CD: 'uow-00' -> '/scratch/gd98309/S2/assemblies/funzip_s2_run5/3-unzip/0-phasing/000243F'
Traceback (most recent call last):
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 116, in <module>
    main()
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 112, in main
    run(**vars(args))
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 65, in run
    pypeflow.do_task.run_bash(script, inputs, outputs, params)
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/site-packages/pypeflow/do_task.py", line 187, in run_bash
    util.system(cmd)
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
2019-01-11 13:25:00,661 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2019-01-11 13:25:00,661 - root - WARNING - CD: '/scratch/gd98309/S2/assemblies/funzip_s2_run5/3-unzip/0-phasing/000243F' -> '/scratch/gd98309/S2/ass
emblies/funzip_s2_run5/3-unzip/0-phasing/000243F'
2019-01-11 13:25:00,661 - root - WARNING - CD: '/scratch/gd98309/S2/assemblies/funzip_s2_run5/3-unzip/0-phasing/000243F' -> '/scratch/gd98309/S2/ass
emblies/funzip_s2_run5/3-unzip/0-phasing/000243F'
2019-01-11 13:25:00,662 - root - CRITICAL - Error in /home/gd98309/.conda/envs/pb-assembly/lib/python2.7/site-packages/pypeflow/do_task.py with args
="{'json_fn': '/scratch/gd98309/S2/assemblies/funzip_s2_run5/3-unzip/0-phasing/000243F/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/site-packages/pypeflow/do_task.py", line 267, in <module>
    main()
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/site-packages/pypeflow/do_task.py", line 259, in main
    run(**vars(parsed_args))
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/site-packages/pypeflow/do_task.py", line 253, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/site-packages/pypeflow/do_task.py", line 228, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/site-packages/pypeflow/do_task.py", line 187, in run_bash
    util.system(cmd)
  File "/home/gd98309/.conda/envs/pb-assembly/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
+++ pwd
++ echo 'FAILURE. Running top in /scratch/gd98309/S2/assemblies/funzip_s2_run5/3-unzip/0-phasing/000243F (If you see -terminal database is inaccessi
ble- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real	0m37.055s
user	0m39.464s
sys	0m5.147s
+ finish
+ echo 'finish code: 1'
```

Any comments?

**Comment by isovic** [comment] 2019-01-15 16:33
Hi,
A new release is now available in Bioconda, and this issue should be fixed. Could you try running it?

Best regards,
Ivan.

**Comment by gbdias** [comment] 2019-01-16 15:33
Hi @isovic ,

- I will give it a try. But do you see anything wrong with this contig's header?
`>000243F 000142541:E~000193175:B~000223649:B~000223649:B ctg_linear 149887 476253`
- The unzipping is crashing at this contig every time, even if I do a new assembly, and the error says something about "cycles in the graph".
- I notice there's two repeated node names there `~000223649:B~000223649:B`. And in a previous successful assembly the same contig has no repeated node names.
`>000243F 000150593:E~000291496:E~000291496:E~000227176:B ctg_linear 94998 385464`

Any thoughts on that?
Thanks

**Comment by gbdias** [comment] 2019-01-24 20:40
- As stated in the first comment, I had been trying to use fasta file generated by an HGAP4 run and bam files generated by the pbsmrtpipe conversion pipeline.
- This page says that those input files are compatible with Falcon (older, non-conda version).
https://pb-falcon.readthedocs.io/en/latest/hgap4_adapt.html
- Because of the errors I was getting (previous posts) I decided to re-generate the input files using the standalone tools [bax2bam](
https://github.com/pacificbiosciences/bax2bam/) v0.0.8 and [bam2fastx](
https://github.com/pacificbiosciences/bam2fastx/) v1.3.0 and re-run the assembly using pb-assembly (v 0.0.1).
- This seems to have solved the problem as the Unzip step has completed successfully and polishing is almost done.
- These experiments suggest the error reported here is not related to pb-assembly versions, but rather to the input files used, and it might be the case that HGAP4 output is not compatible with pb-assembly.
- @isovic please let me know if you have a different interpretation on these tests.

**Comment by isovic** [comment] 2019-02-05 11:32
Hi @gbdias,
Your observations about that particular contig's path are correct (`000243F`).
In some cases, chimeric reads in the input (which weren't successfully clipped/thrown away) can cause small circular contigs to appear as a product of the assembly. Circular contigs on their own are not a problem, but in your example there is a cyclic tiling path edge which folds back to the same node which is also an internal node of the same tiling path (coincidentally, the last node of the path). This is likely a palindromic read caused by a missing adapter.
The new version of Unzip handles such cases without throwing an exception. If you however decide to stick with an old version, you can remove this contig from your `2-asm-falcon/p_ctg.fa` file, and try running Unzip from scratch.

**Comment by isovic** [comment] 2019-02-05 11:38
In this sense, as you've already observed, different filtering of input data could play a role in the contigs you generated.
But, what's perhaps even more important, are the settings used for assembly. In your FALCON and HGAP4 assemblies, have you used the exact same parameters?
Some settings which could impact these results are the ones related to Daligner overlapping, error correction and overlap filtering.

> These experiments suggest the error reported here is not related to pb-assembly versions, but rather to the input files used, and it might be the case that HGAP4 output is not compatible with pb-assembly.
The "error" was put there as a safeguard to catch strange contigs before they enter Unzip. This approach has been reworked now in the new versions.

**Comment by gbdias** [comment] 2019-02-05 15:46
Hi @isovic ,
- The settings for HGAP4 and Falcon are different. For HGAP4 I am using the defaults in SMRTlink 5.1.0, and for Falcon + Unzip I modified the config file following Greg Concepcion's github repo and the Daligner blog.
- In any case, regenerating the input files from the original bax.h5 instead of using HGAP4 output solved the problem, and no circular cyclic tiling paths were generated apparently.
- Do you think **bax2bam** and **bam2fasta** are removing these chimeric reads? And if so, the pbsmrtpipe bam conversion is not?

Thanks for your input!
Guilherme

**Comment by isovic** [comment] 2019-02-14 17:29
Hi Guilherme,

> * Do you think **bax2bam** and **bam2fasta** are removing these chimeric reads? And if so, the pbsmrtpipe bam conversion is not?

No, that really should not be the case. It's most likely that this is due to the difference in the used config parameters.

I'm happy to hear that you successfully moved past this issue! I'll close it now, but if you run into it again, feel free to reopen.

Thank you,
Best regards,
Ivan.

**Closed by isovic** 2019-02-14 17:29 UTC
Labels: Assembly
